### ISSUE TITLE
ToDo list before public launch (website and polish)

### ISSUE THREAD

**Issue by synctext** [Tribler/trustchain-superapp#31]
- [X] Contact Tweakers for interested in a story.
- [X] First draft of website (https://synctext.github.io/)
- [ ] Decide on storyline and theme (normal people don't know what a DAO is, impossible to explain)
  - replace _Take back our economy !!_
  - use "fully automated luxury communism"? (let robots do all the work)
  - See https://www.theguardian.com/books/2019/may/29/fully-automated-luxury-communism-aaron-bastani-review and https://www.theatlantic.com/ideas/archive/2019/06/give-us-fully-automated-luxury-communism/592099/
- [ ] make website professional @emieldesmidt ?
- [ ] do an official superapp release
  - [X] integrated crash reporter
  - [ ] Merge DAO into master
  - [ ] do RC1 testing on forum-tribler.org and Twitter post
  - [ ] test DAO with real Bitcoins and 6 members.
- [ ] Contact journalist for story (3-days writeup)
- [ ] DEADLINE: 12 May for website ready and 14th for story post.

**Comment by devos50** [comment]
You might want to consider contacting the [Redecentralized team](https://redecentralize.org/#contact) to get included in [their monthly digest](https://redecentralize.org/redigest/). They particular appreciate these kind of freedom fighting projects 👍

**Comment by MattSkala** [comment]
DAO is now merged into master and v0.1 released on [GitHub Releases](https://github.com/Tribler/trustchain-superapp/releases)
